### PR TITLE
Add GetClusterSetName to get the name of the ManagedClusterSet from the ManagedCluster's clusterSet label.

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
@qiujian16 could you please take a look and provide some feedback? Thanks.

**Comment by qiujian16** [comment]
this won't work when we add labeSelector based clusterset. I think we should use GetClusterSetsOfCluster.

**Comment by mikeshng** [comment]
> this won't work when we add labeSelector based clusterset. I think we should use GetClusterSetsOfCluster.

Thanks. Closing.

**Pull request closed without merging**
