### PR TITLE
add short name mcl for managedCluster

### PR DESCRIPTION
**Pull request by zhiweiyin318**
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
story:  https://github.com/open-cluster-management/backlog/issues/12424

### CODE REVIEW

**Comment by qiujian16** [comment]
/lgtm

will need opinion from David on this short name.

/assign @deads2k

**Comment by deads2k** [comment]
Rather than one at a time, can you make a list of the APIs in this repo, indicate which ones you think deserve a shortname, and what that shortname will be?

I'm trying to decide how well the pattern holds up if we decide that manageclustersets or managedclustersetbindings need short name: mcls?  I think the plural appearance makes it hard to reason about.  mcsets? mclsets? (do we even need a shortname for these?

**Comment by zhiweiyin318** [comment]
@qiujian16 @deads2k  please review the short names of APIs.

A simple short name pattern for the name beginning with cluster/managedcluster/placement:
- cluster -- cl
- managedcluster -- mcl
- placement -- pl
- clusterXXX/managedclusterXXX/placementXXX -- cl/mcl/plXXX

the short name lists:
| API | singular | plural |  
|---|---|---|
| clustermanagementaddons.addon.open-cluster-management.io | clmaddon | clmaddons |
| managedclusteraddons.addon.open-cluster-management.io | mcladdon | mcladdons |
| managedclusters.cluster.open-cluster-management.io  |  mcl  |  mcls  |
| managedclustersets.cluster.open-cluster-management.io | mclset | mclsets |
| managedclustersetbindings.cluster.open-cluster-management.io | mclsetbinding | mclsetbindings |
| clusterclaims.cluster.open-cluster-management.io | clclaim | clclaims |
| placements.cluster.open-cluster-management.io | pl | pls |
| placementdecisions.cluster.open-cluster-management.io | pldecision | pldecisions |
| klusterlets.operator.open-cluster-management.io | kl | kls |
| clustermanagers.operator.open-cluster-management.io | clmgr | clmgr |
| manifestworks.work.open-cluster-management.io | mwork | mworks |
| appliedmanifestworks.work.open-cluster-management.io | \ | \ | 

ignore appliedmanifestworks since it is rarely used by users via terminal.

**Comment by deads2k** [comment]
Ok, thanks for writing them all out, it helps to see where we could go and extend the pattern.  The `clmaddon` and `mcladdon` are muddy distinctions when abbreviated, I think I would skip those.  I think I'm -1 on `kl` and `mwork` given a length savings to legibility ratio.

Based on this list, I'm good to start with all the `mcl*` names.  I think I would hold off on `cl*` (it's not that many characters saved).

**Comment by zhiweiyin318** [comment]
thanks for the comments from @deads2k . let's start with the mcl* . 

A simple short name pattern for the name beginning with managedcluster:
- managedcluster -- mcl
- managedcluster*- mcl*

the given short name lists:
| API | singular | plural |  
|---|---|---|
| managedclusters.cluster.open-cluster-management.io  |  mcl  |  mcls  |
| managedclustersets.cluster.open-cluster-management.io | mclset | mclsets |
| managedclustersetbindings.cluster.open-cluster-management.io | mclsetbinding | mclsetbindings |

will give short name to the other APIs if have better options in the future.

**Pull request merged**
