### PR TITLE
:seedling: Add `Ignore` rollout status

### PR DESCRIPTION
**Pull request by dhaiducek**
## Summary

An `Ignore` rollout status in my reading of it felt different than a `Skip` status, where `Ignore` would mean that it wouldn't factor into a rollout but would receive updates while `Skip` would mean it didn't receive updates, but I'm open to discussion on it.

I also have an optional commit here to add `RolloutType` to make the enum a bit more concrete.

## Related issue(s)

- #254

### CODE REVIEW

**Comment by haoqing0110** [comment]
For the skip status, when adding it, expect it to be a status return from ClusterRolloutStatusFunc by API consumers, indicating that the consumers do not want to do a rollout on this cluster. 
For the ignore status, not sure what does "receive updates" mean? in the PR seems ingore returns the same value as skip.

**Comment by dhaiducek** [comment]
/hold

> For the skip status, when adding it, expect it to be a status return from ClusterRolloutStatusFunc by API consumers, indicating that the consumers do not want to do a rollout on this cluster. For the ignore status, not sure what does "receive updates" mean? in the PR seems ingore returns the same value as skip.

Thanks for the feedback. We want users to be able to specify that a particular cluster should get updated in the rollout but it doesn't matter to them whether the status is returned successful. It seems adding `Ignore` is confusing, so we're going to consider this further. For this it seems like we should just use `Succeeded` if it succeeds but add a `FailedNonBlocking` status instead of `Ignore` to say that the library is aware it failed during the rollout but is continuing on.

**Pull request closed without merging**
