### PR TITLE
Update crd version to v1

### PR DESCRIPTION
**Pull request by qiujian16**
Signed-off-by: Jian Qiu <jqiu@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
/hold

I  think we still need to keep the v1beta crds for older version kube support. I will figure it out

**Comment by deads2k** [comment]
wow, that will make you go cross-eyed.  I *think* it's equivalent.  Have you tried comparing the `oc get crd/foo -oyaml` output before and after to see if it's the same? I don't actually know for sure it will be, but that would be very convenient.

/approve
/hold

holding until someone fully diffs (hopefully by machine) the difference.

**Comment by deads2k** [comment]
This is an important change since CRD v1beta1 is being removed in 1.22.  One detail to note about the change is that these manifests will not work on openshift 3.11 if that is still and objective.

**Comment by qiujian16** [comment]
@deads2k I create a script to apply the  current main branch and get the  spec,  then apply the v1 version  and get the spec. Finally i compare the before/after spec.  I do not think this script should be put in the pr since it is just to verify the change once. 

```sh
#!/bin/sh

git checkout main

FILES="cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
cluster/v1alpha1/0000_00_clusters.open-cluster-management.io_managedclustersets.crd.yaml
cluster/v1alpha1/0000_01_clusters.open-cluster-management.io_managedclustersetbindings.crd.yaml
cluster/v1alpha1/0000_02_clusters.open-cluster-management.io_clusterclaims.crd.yaml
work/v1/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
work/v1/0000_01_work.open-cluster-management.io_appliedmanifestworks.crd.yaml
operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
operator/v1/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml
addon/v1alpha1/0000_00_addon.open-cluster-management.io_clustermanagementaddons.crd.yaml
addon/v1alpha1/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml
"

crdNames="managedclusters.cluster.open-cluster-management.io
managedclustersets.cluster.open-cluster-management.io
managedclustersetbindings.cluster.open-cluster-management.io
clusterclaims.cluster.open-cluster-management.io
manifestworks.work.open-cluster-management.io
appliedmanifestworks.work.open-cluster-management.io
klusterlets.operator.open-cluster-management.io
clustermanagers.operator.open-cluster-management.io
clustermanagementaddons.addon.open-cluster-management.io
managedclusteraddons.addon.open-cluster-management.io
"

for f in $FILES
do
    kubectl apply -f $f
done

for crd in $crdNames
do
  kubectl get crd $crd -o jsonpath='{.spec}' > $crd-before
done

git checkout crd-v1

for f in $FILES
do
    kubectl apply -f $f
done

for crd in $crdNames
do
  kubectl get crd $crd -o jsonpath='{.spec}' > $crd-after
done

for crd in $crdNames
do
  diff -u $crd-before $crd-after
done

for crd in $crdNames
do
  kubectl delete crd $crd
  rm $crd-before
  rm $crd-after
done
```

**Comment by deads2k** [comment]
That's a great script. Would you open a PR to openshift/api with it?

/lgtm
/approve

**Pull request merged**
