### PR TITLE
move registration feature gates to api, can be used by registration-o…

### PR DESCRIPTION
**Pull request by ivan-cai**
move registration feature gates to api, can be used by registration-operator for check input feature gates if valid.

Signed-off-by: ivan-cai <caijing.cai@alibaba-inc.com>

### CODE REVIEW

**Comment by ivan-cai** [comment]
@qiujian16 As we discussed in  [registration-operator pr 230](https://github.com/open-cluster-management-io/registration-operator/pull/230)

**Review by qiujian16 — COMMENTED** [review]
hrm, could we just define the feature name or feature spec in api? I do not think we should have init here, this could be messy when others import api given feature is a global var.

**Comment by ivan-cai** [comment]
> hrm, could we just define the feature name or feature spec in api? I do not think we should have init here, this could be messy when others import api given feature is a global var.

@qiujian16 I have delete `init()` and `DefaultSpokeMutableFeatureGate` & `DefaultHubMutableFeatureGate`. Plz review again.

**Comment by qiujian16** [comment]
thanks, one more nit thing. How about we have a separate package like `feature` to put it? I do not think it relates to a certain version of API, right?

**Comment by ivan-cai** [comment]
> thanks, one more nit thing. How about we have a separate package like `feature` to put it? I do not think it relates to a certain version of API, right?

@qiujian16 Yes, I have changed. Plz review again, thanks!

**Pull request merged**
