### PR TITLE
✨ Allow custom signer signingCA to specify namespace in addOnTemplate

### PR DESCRIPTION
**Pull request by zhujian7**
## Related issue(s)
https://github.com/open-cluster-management-io/ocm/issues/688

Fixes #

### CODE REVIEW

**Review by mikeshng — APPROVED** [review]
/lgtm

Thanks Zhu Jian! Exactly what I needed!

**Comment by qiujian16** [comment]
@zhujian7 I think addon manager will not by default has secret access permission for any ns? It has to be added on demand, right?

**Comment by zhujian7** [comment]
> @zhujian7 I think addon manager will not by default has secret access permission for any ns? It has to be added on demand, right?

yes, the developer needs to ensure the addon-manger has the permission. I have added on the field comment

**Pull request merged**
