### PR TITLE
add pattern for clustername

### PR DESCRIPTION
**Pull request by ycyaoxdu**
related issue: https://github.com/open-cluster-management-io/clusteradm/issues/318

### CODE REVIEW

**Comment by ycyaoxdu** [comment]
/assign @qiujian16 
cc @mikeshng

**Comment by qiujian16** [comment]
not quite sure if it is breaking. We need a discussion on this
Also since it needs to be comply with namespace format, we might also set maxLength to 63?

**Comment by qiujian16** [comment]
@ycyaoxdu would you rebase the PR I think we can merge this one

**Pull request merged**
