### PR TITLE
🐛 support update&updateStatus for manifestwork cloudevents client.

### PR DESCRIPTION
**Pull request by morvencao**
## Summary

This PR introduces the addition of 'Update' and 'UpdateStatus' functionalities for the manifestwork cloudevents client. These methods are necessary as the work-client implementation will use them, but currently the manifestwork cloudevents client only includes 'Get' and 'Patch'.

### CODE REVIEW

**Comment by skeeey** [comment]
@morvencao the newest work-agent in ocm only use patch way to update mw or it's status, this is why we only implement the patch way for the agent mw client :)

**Comment by morvencao** [comment]
closing this as the new work-agent only needs `patch`.

**Pull request closed without merging**
