### PR TITLE
🌱 Regenerate informers with WithTransform

### PR DESCRIPTION
**Pull request by skitt**
## Summary

Since 1.29, Kubernetes supports transforming informers, which is useful to reduce the amount of memory used by the underlying caches. This updates the code generator to the latest 0.29 release and re-generates the informers.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by vthapar** [comment]
Can we get review on this? This will be very helpful for optimization work we're doing on SubmarinerAddon.

**Comment by qiujian16** [comment]
would you run go mod tidy and go mod vendor?

**Comment by skitt** [comment]
> would you run go mod tidy and go mod vendor?

I’d already done that, the verify-deps failure happened because CI was set up for Go 1.20 and the build now requires 1.21.

**Pull request merged**
