### PR TITLE
add v1beta2 clusterset

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/open-cluster-management-io/OCM/issues/67

### CODE REVIEW

**Comment by qiujian16** [comment]
is it v1beta2?

**Comment by ldpliu** [comment]
> is it v1beta2?

Yes, changed it.

**Comment by ldpliu** [comment]
/cc @qiujian16 @elgnay 
I add the conversion webhook logic in this pr, please help to review it again.
Thanks

**Pull request merged**
